{
	"version": 1543493682,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/bullet-sheet0.png",
		"images/explosion-sheet0.png",
		"images/monster-sheet0.png",
		"images/menuitembackground.png",
		"images/treasure-sheet0.png",
		"images/immortal-sheet0.png",
		"images/wasd-sheet0.png",
		"images/mouse2-sheet0.png",
		"images/mouse3-sheet0.png",
		"images/back-sheet0.png",
		"images/back-sheet1.png",
		"media/ngoec.m4a",
		"media/ngoec.ogg",
		"media/gunshot.m4a",
		"media/gunshot.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/11 - battle 2014.m4a",
		"media/11 - battle 2014.ogg",
		"media/ak47-sfx - part.ogg",
		"media/uzi-burst - part.ogg",
		"media/m16-triburst - part.ogg",
		"media/mosin - part.ogg",
		"media/machine-gun-001-triple-shot - part.ogg",
		"media/paintball-gun-shots - part.ogg",
		"media/galil-reload-sound.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}